### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Chris1504-fdz** [AMReX-Microelectronics/MagneX#62]
I had problems doing git clone as instructed in the READ ME section, this link seems to have a typo: "https://AMReX-Microelectronics/MagneX.git" this is the link I used: "https://github.com/AMReX-Microelectronics/MagneX.git"

**Comment by ajnonaka** [comment]
Thank you! - fixed with https://github.com/AMReX-Microelectronics/MagneX/pull/84
